### ISSUE TITLE
make Actions

### ISSUE THREAD

**Issue by adamaltman** [garcijo/testProject#6]
Instead of using closures to define your routes, you can use a class/method.  For example:

`$app->get('/signup', SignUpPageAction::class);`

To do that, you'll need to make those classes.  Each action should be a separate class, and it would likely implement this method:

`public function __invoke(Request $request, Response $response, $args)`

**Comment by garcijo** [comment]
All the code in routes has now been refactored into action classes.

**Comment by adamaltman** [comment]
Hmmm, do you know how to link pull requests to issues?
